### ISSUE TITLE
Misaligned on Live Preview mode

### ISSUE THREAD

**Issue by akadormouse** [chetachiezikeuzor/Highlightr-Plugin#13]
On Live Preview, the highlights are slightly below the target words. All is corrected when the plugin is turned off.

**Comment by chetachiezikeuzor** [comment]
Hello! Is there any way you could include a screenshot of this bug? It would help in finding the issue. Thanks!

**Comment by akadormouse** [comment]
![image](https://user-images.githubusercontent.com/91322324/142722760-6ee3ad9a-46cb-4954-a257-ea677ad74e73.png)

The roger and rich are highlighted with your plugin. Roast is just the plain == Obsidian highlighting.
All other plugins turned off.

Obsidian 0.13.4
Live Preview turned on

**Comment by chetachiezikeuzor** [comment]
Thank you very much for your screenshot. Do you happen to have the setting for highlight style changed? And does this happen in other themes as well?

**Comment by akadormouse** [comment]
Happens in default theme.

**Highlight styles:**
This came from lowlight (hadn't realised it was anything but normal) which I assume looked fine to me until the Live Preview version came out.
Floating is even lower,
None, rounded and realistic seem fine.
So maybe just me.
Thanks.

**Comment by chetachiezikeuzor** [comment]
Yea I had a feeling that this was one of the highlight settings. [Lowlight](https://www.google.com/amp/s/beatrizcaraballo.com/blog/low-highlight-heading-links-squarespace%3fformat=amp) will make the highlights looks like they're cut in half horizontally. And floating makes it look like the text has a thick underline. Do these styles looks the same in Live Preview as they do with regular view?

**Comment by akadormouse** [comment]
An explainer would be good; image helpful. Calling floating underline would be more obvious.

What I find strange, is that I would have gone through the styles to see what they were and would never have liked lowlight. I can't revert editor to check, but it's not just Live Preview now, and I assume it's my misinterpreting the style as a change with CM6. Still, no problem now, very sorry for false alarm and time waste, Thank You.

**Comment by chetachiezikeuzor** [comment]
No worries at all! And thank you for your tips. I will be adding some more info in the readme for other users so no time has been wasting chatting with you! 🤗
