### ISSUE TITLE
Can't find `main.js`

### ISSUE THREAD

**Issue by Andrii256** [chetachiezikeuzor/Highlightr-Plugin#14]
I found only main.ts file, but can't find main.js here. Maybe because of you added `main.js` into `.gitignore`

**Comment by Andrii256** [comment]
After I run 'npm run build' in command line it (main.js) appeared.

**Comment by ryanpcmcquen** [comment]
It is only supposed to be included in releases.

**Comment by chetachiezikeuzor** [comment]
Like @ryanpcmcquen mentioned, your best bet is to install the plugin through the available releases:

https://github.com/chetachiezikeuzor/Highlightr-Plugin/releases/tag/1.1.2

This will prevent you from having to build the source files.

**Comment by Andrii256** [comment]
@ryanpcmcquen , @chetachiezikeuzor , thank you
Ashamed to confess, but I didnt know about "releases" in right part of "code" tab
