### ISSUE TITLE
Add command for unhighlighting

### ISSUE THREAD

**Issue by phlind** [chetachiezikeuzor/Highlightr-Plugin#4]
First of all, thanks for this great plugin. ❤️ 

Would it be possible to add a command (which includes the possibility to assign a hotkey) for unhighlighting? This would make it easier to just work with the keyboard.

Thanks!

**Comment by D1yt** [comment]
Hey @chetachiezikeuzor, I have some suggestions following up this request:
1) Could you add the toggle/removal of highlights on application of same color, when there is no word selected in the editor, but the text-cursor is in a highlighed phrase? Right now this just places an empty highligher (no text). Having to mark the whole phrase can be time-consuming and prone to fail. I want what the keybind for removing highlights already does, but as a default when not marking words or phrases.
2) This should also work for recoloring, e.g. replacing the color in the highlighed phrase the text-cursor is placed in.

3) With this, you could also add a "Remove color"-option in the highlight-selector.

Those first two features should essentially work like how built-in shortcuts (for example ctlr+b for bolt) behave.
For this, you might also want to consider that:
1) the text-cursor should be moved to the beginning of the highlighed phrase (if possible even to the text position you clicked), when you click on it, so it is inside the highlight tags and you don't need a double click to remove the highlight
2) the highlighting shortcut should highlight the whole word, when it is not selected but the text-cursor is "inside"
