### ISSUE TITLE
highlightr broken in 0.15.9 even after latest update

### ISSUE THREAD

**Issue by KraXen72** [chetachiezikeuzor/Highlightr-Plugin#47]
![image](https://user-images.githubusercontent.com/21956756/187908964-aaf9fd69-2080-40b8-b2f6-f954be82ac7f.png)
doesen't create the right click menu for "highlight" at all

**Comment by chetachiezikeuzor** [comment]
Geez, alright I understand the issue now. I'm using a function in the new update that's only available in Obsidian 0.16.0 Insider build. Sorry for this, I'll fix this as soon as possible. Thank you for your patience!

**Comment by boyuanmby** [comment]
KraXen72, I encountered the same problem. Thank you for putting your issue here!
Chetachi, Thank you for developing such a great plugin!

**Comment by tankilo** [comment]
Expect this problem to be fixed.

**Comment by cremepvff** [comment]
highlighter is still not working, unsure if this has been fixed yet

**Comment by dlion** [comment]
Yep, it is still broken.
@chetachiezikeuzor Do you have any ETA for this?

---

UPDATE: uh, I saw that with the last commit, the problem had been fixed: https://github.com/chetachiezikeuzor/Highlightr-Plugin/commit/61341a464456cdc868ffa1480341136025ec8389, but I guess we still don't have a plugin update.
Patching the local version it works again

**Comment by yarub123** [comment]
@dlion Hey dude from 2 years ago. Hope you're well. 

Just curious how would I go about locally patching it? I'm browsing the files of that commit that you mentioned but don't see main.js (probably since it's on "releases.") Is there a way to go about doing it?

**Comment by dlion** [comment]
Hey @yarub123 , I think the issue was fixed a long time ago.
BTW if you want to have a local patch you can edit the local version of the plugin. For example, in this case, you can just find your Highlightr plugin folder, find the file `src/ui/highlighterMenu.ts`, and edit it. Re-open Obsidian and done.
Be aware that every time you update the plugin your changes will be overridden.

**Comment by yarub123** [comment]
@dlion Good man. Appreciate the response. I figured it out yesterday. Something was wrong with my obsidian, a simple restart fixed it. I forgot to update my comment in here, but it's still good to know. Thanks again brotha.
