### ISSUE TITLE
Dracula Official

### ISSUE THREAD

**Issue by Ducky6944** [chetachiezikeuzor/Highlightr-Plugin#56]
All highlight colors show as yellow regardless of the selected color. Adding `!important` seems to work.

**Comment by juliagng** [comment]
I use the 'Pink Topaz (Legacy)' theme, all highlight colors appear as red for me. Would really appriciate if it gets fixed :)

**Comment by Chrismettal** [comment]
A fix was merged into the Dracula theme itself. Themes setting `!important` on themed elements make it harder for plugins to overwrite these elements. Thanks @lucasrabiec!

**Comment by Ducky6944** [comment]
This is fixed for dracula so I will close this issue. @lucasrabiec thank you! @Chrismettal  Thanks for the heads up!
