### ISSUE TITLE
FR: Add Unhighlight Command

### ISSUE THREAD

**Issue by nothingislost** [chetachiezikeuzor/Highlightr-Plugin#6]
Unhighlight should be a command so that it can be bound to a cMenu button. Or better yet, add logic into generateCommands() to check the highlighted text, and if it starts with `<mark>` then the action should be unhighlight rather than a second highlight wrapper. This way you can toggle the highlight with a single button.

**Comment by chetachiezikeuzor** [comment]
I've just added an unhighlight command! Also, it *sorta* has logic built into it that does this, but it isn't at all perfect. If you highlight a word with a certain color, then highlight that word with the same color, it will remove the highlight. But if you highlight it with a different color, it'll just add another highlight. I'm still working on how to make this better. 

https://user-images.githubusercontent.com/79069364/137416259-124941be-2beb-41b0-b2af-958cec865b82.mp4

**Comment by chetachiezikeuzor** [comment]
Ran into some issues with this (*sigh*). I'll keep working on it.

**Comment by chetachiezikeuzor** [comment]
Okay, I think I've got it. It will find if prefix ends with `>`, suffix is `</mark>`,  and that you have selected text. Then, it will remove the highlight. 

https://user-images.githubusercontent.com/79069364/137419277-867e6af3-a1c4-46e7-86ee-760dd352053d.mp4

**Comment by nothingislost** [comment]
NIce! 👍
