### ISSUE TITLE
Suggestion: Set the cursor to one character after the mark close tag

### ISSUE THREAD

**Issue by nothingislost** [chetachiezikeuzor/Highlightr-Plugin#7]
Upon highlight, you may want to consider moving the cursor to one character after the `</mark>`. I'm sure there's different opinions where the cursor should end up but if you place it one character after the close tag, it will allow for my plugin to do this:

![2021-10-14 15 44 43](https://user-images.githubusercontent.com/89109712/137405504-5be8b626-7eb1-4ff6-951c-ddf4c69c9a7e.gif)

since the HTML rendering functionality will only apply once the cursor moves away from the code.

**Comment by chetachiezikeuzor** [comment]
Interesting. Hmm, the issue with this is that the plugin also lets you highlight even when you don’t have text selected, and it would be weird to select text, highlight and have your cursor set outside the highlight. I guess what could be done is to find if something has been selected, then set the cursor to be inside the highlight. Then if something isn’t selected, set it to be outside. Or I could just make it a setting in the settings tab.

**Comment by chetachiezikeuzor** [comment]
Something like this? Also there's a command to open the highlighter called "Highlightr: Highlight"

https://user-images.githubusercontent.com/79069364/137414781-7d19f582-87ea-4667-81d8-bf78c96e4f18.mp4

**Comment by nothingislost** [comment]
yeah, that looks like sane behavior to me 👍
